# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.3
_src_path: https://github.com/calliecameron/copier-template
author_name: Callie Cameron
copyright_start_year: '2023'
exports_requirements_txt: false
github_repo: calliecameron/mrpack-utils
project_name: Mrpack
user_has_css: false
user_has_html: false
user_has_javascript: false
user_is_python_package: true
user_uses_bats: false
