[project]
name = "mrpack"
version = "0.0.0"
description = "Utilities for working with Modrinth-format (mrpack) Minecraft modpacks"
readme = "README.md"
requires-python = "==3.14.*"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Callie Cameron", email = "cjcameron7@gmail.com" }]
dependencies = [
  "attrs==23.2.0",
  "frozendict==2.4.6",
  "jsonschema==4.25.1",
  "requests==2.32.5",
  "tabulate==0.9.0",
]

[project.scripts]
mrpack = "mrpack.main:main"

[dependency-groups]
dev = [
  "ast-grep-cli==0.39.9",
  "bump-my-version==1.2.4",
  "cookiecutter==2.6.0",
  "copier==9.10.3",
  "copier-template-extensions==0.3.3",
  "frozendict==2.4.6",
  "gha-update==0.2.0",
  "gitlint==0.19.1",
  "identify==2.6.15",
  "licensecheck==2025.1.0",
  "mypy==1.18.2",
  "packaging==25.0",
  "pre-commit==4.4.0",
  "pytest==9.0.0",
  "pytest-cov==7.0.0",
  "pytest-custom_exit_code==0.3.0",
  "requests-mock==1.12.1",
  "ruff==0.14.4",
  "shellcheck-py==0.11.0.1",
  "tombi==0.6.42",
  "types-jsonschema==4.25.1.20251009",
  "types-requests==2.32.4.20250913",
  "types-tabulate==0.9.0.20241207",
  "typos==1.39.0",
  "yamllint==1.37.1",
  "zizmor==1.16.3",
]

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"

[tool.bumpversion]
[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "src/mrpack/__init__.py"
search = "__version__ = \".*\""
regex = true
replace = "__version__ = \"{new_version}\""

[tool.coverage.run]

[tool.mypy]
explicit_package_bases = false
mypy_path = "stubs"
namespace_packages = false
pretty = true
scripts_are_modules = true
strict = true

[tool.pytest.ini_options]
addopts = "--strict-markers --suppress-no-test-exit-code --cov=mrpack --cov-report=term-missing"
markers = ["slow"]

[tool.ruff]
namespace-packages = [
  ".template_files",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "C90",  # mccabe:*
  "D1",  # pydocstyle:undocumented-*
  "E741",  # pycodestyle:ambiguous-variable-name
  "EM",  # flake8-errmsg:*
  "FIX",  # flake8-fixme:*
  "PLR09",  # refactor:too-many-*
  "PT011",  # flake8-pytest-style:pytest-raises-too-broad
  "PTH",  # flake8-use-pathlib:*
  "PYI025",  # flake8-pyi:unaliased-collections-abc-set-import
  "S603",  # flake8-bandit:subprocess-without-shell-equals-true
  "S607",  # flake8-bandit:start-process-with-partial-path
  "T20",  # flake8-print:*
  "TD",  # flake8-todos:*
  "TRY003",  # tryceratops:raise-vanilla-args
  "TRY301",  # tryceratops:raise-within-try
]

[tool.tombi]

[tool.typos]
files.extend-exclude = [
  "/.copier-answers.yml",
]
default.extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker: *disable-line$",
  "(?s)(#|//)\\s*spellchecker:* off.*?\\n\\s*(#|//)\\s*spellchecker:* on",
  "(#|//)\\s*spellchecker:* disable-next-line\\n.*",
]

[tool.uv]
package = true
