#!/bin/bash

set -eu

if [ ! -e pyproject.toml ]; then
    echo 'Must be run in the root of the project' 1>&2
    exit 1
fi

function usage() {
    echo "Usage: $(basename "${0}") [--requirements-txt]" 1>&2
    exit 1
}

EXPORT_REQUIREMENTS=''
if [ -n "${1:-}" ]; then
    if [ "${1}" = '--requirements-txt' ]; then
        EXPORT_REQUIREMENTS='t'
    else
        usage
    fi
fi

uv sync --all-extras --all-groups

if [ -n "${EXPORT_REQUIREMENTS}" ]; then
    uv export --quiet --output-file=requirements.txt --all-extras --no-default-groups
fi
